export const TRACKS_FETCH_REQUEST = 'TRACKS_FETCH_REQUEST';
export const TRACKS_FETCH_SUCCESS = 'TRACKS_FETCH_SUCCESS';
export const TRACKS_FETCH_FAILURE = 'TRACKS_FETCH_FAILURE';

export const TRACK_SET = 'TRACK_SET';
